/**
 * useOewsState
 *
 * Fetches and caches the pre-processed BLS OEWS state-level JSON file
 * (public/oews_state.json, generated by scripts/processBlsData.mjs).
 *
 * Data source: BLS OEWS May 2024 state estimates (state_M2024_dl.xlsx)
 * Vintage: May 2024
 *
 * Provides helpers to access:
 *  - State-level wages, percentiles, employment, location quotient
 *  - Nonmetro balance area data for metro/nonmetro comparison
 *  - State rankings sorted by annual mean wage
 */
import { useState, useEffect, useMemo } from 'react'

const CACHE_KEY = 'oews_state_v1'
const CACHE_TTL = 24 * 60 * 60 * 1000

function readCache(key) {
  try {
    const raw = sessionStorage.getItem(key)
    if (!raw) return null
    const { data, ts } = JSON.parse(raw)
    if (Date.now() - ts > CACHE_TTL) { sessionStorage.removeItem(key); return null }
    return data
  } catch { return null }
}

function writeCache(key, data) {
  try { sessionStorage.setItem(key, JSON.stringify({ data, ts: Date.now() })) } catch {}
}

let _inFlight = null // shared promise so multiple callers don't double-fetch

export function useOewsState(occCode) {
  const [db, setDb] = useState(() => readCache(CACHE_KEY))
  const [loading, setLoading] = useState(!db)
  const [error, setError] = useState(null)

  useEffect(() => {
    if (db) return
    if (!_inFlight) {
      _inFlight = fetch(`${import.meta.env.BASE_URL}oews_state.json`)
        .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json() })
        .then(json => { writeCache(CACHE_KEY, json); return json })
    }
    _inFlight
      .then(json => { setDb(json); setLoading(false) })
      .catch(err => { setError(err.message); setLoading(false) })
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // Data for the currently selected occupation
  const occData = useMemo(() => {
    if (!db || !occCode) return null
    return db.occupations?.[occCode] ?? null
  }, [db, occCode])

  // All states sorted by a_mean descending (for rankings)
  const stateRankings = useMemo(() => {
    if (!occData?.states) return []
    return Object.entries(occData.states)
      .map(([name, d]) => ({ name, ...d }))
      .filter(d => d.a_mean != null)
      .sort((a, b) => b.a_mean - a.a_mean)
  }, [occData])

  // Nonmetro entries for this occupation (metro/nonmetro comparison)
  const nonmetroEntries = useMemo(() => {
    if (!occData?.nonmetro) return []
    return Object.entries(occData.nonmetro).map(([name, d]) => ({ name, ...d }))
  }, [occData])

  // National totals derived from state aggregates (approximate)
  const derivedNational = useMemo(() => {
    if (!occData?.states) return null
    const states = Object.values(occData.states)
    const withEmp = states.filter(s => s.tot_emp != null)
    const withWage = states.filter(s => s.a_mean != null)
    if (!withWage.length) return null
    const totalEmp = withEmp.reduce((s, d) => s + d.tot_emp, 0)
    const wtdWage = withWage.reduce((s, d) => s + (d.a_mean * (d.tot_emp || 0)), 0)
    const wtdTotal = withWage.filter(s => s.tot_emp != null).reduce((s, d) => s + d.tot_emp, 0)
    return { tot_emp: totalEmp, a_mean_est: wtdTotal > 0 ? Math.round(wtdWage / wtdTotal) : null }
  }, [occData])

  function getStateData(stateName) {
    return occData?.states?.[stateName] ?? null
  }

  return { loading, error, occData, stateRankings, nonmetroEntries, derivedNational, getStateData, vintage: db?.vintage }
}
